#!/usr/bin/env bash

hugo -DF | tee hugo.log

node code/render.js
mkdir -p proofs

for i in $*
do
  i=${i#content}
  i=${i%.md}
  src=public/_prince${i}/index.html
  
  pdf=proofs/${i##*/}.pdf
  
  prince $src -o $pdf --fileroot=public/
  open $pdf
done
